// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'customer_login.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CustomerLogin _$CustomerLoginFromJson(Map<String, dynamic> json) =>
    CustomerLogin(
      json['primarycode'] as String,
      json['companycode'] as String,
      json['saleunit'] as String,
      json['customercode'] as String,
      json['customername'] as String,
      json['address'] as String,
      json['tel'] as String,
      json['typeCode'] as String,
      json['taxno'] as String,
      json['priceLevel'] as String,
      json['provinceId'] as String,
      json['provinceName'] as String,
      json['ampherId'] as String,
      json['ampherName'] as String,
      json['townId'] as String,
      json['townName'] as String,
      json['zip'] as String,
      json['lat'] as String,
      json['lon'] as String,
      json['branch'] as String,
      json['activeStatus'] as String,
      json['email'] as String,
      json['mobileno'] as String,
      json['contactperson'] as String,
      json['updatedate'] as String,
      json['applydate'] as String,
      json['salespersonCode'] as String,
      json['salesPersonName'] as String,
      json['saleuniTName'] as String,
      json['tier'] as String,
      json['mobilESales'] as String,
      json['mapCode'] as String,
      json['birthDate'] as String,
      json['gender'] as String,
      json['agentCode'] as String,
      json['jtoken'] as String,
      json['paramValues1'] as String,
      json['paramValues2'] as String,
      json['paramValues3'] as String,
      json['paramValues4'] as String,
      json['paramValues5'] as String,
      json['shopPhotoImage'] as String,
      json['picFileName'] as String,
      json['personType'] as int,
      json['accountCode'] as String,
      json['routeStep2'] as String,
      json['authorizeAmount'] as int,
      json['debtAmount'] as int,
      json['activeDc'] as String,
      json['activeDcName'] as String,
      json['activeDeliveryRoute'] as String,
      json['activeSaleCode'] as String,
      json['activeSalesAreaCode'] as String,
    );

Map<String, dynamic> _$CustomerLoginToJson(CustomerLogin instance) =>
    <String, dynamic>{
      'primarycode': instance.primaryCode,
      'companycode': instance.companyCode,
      'saleunit': instance.saleUnit,
      'customercode': instance.customerCode,
      'customername': instance.customerName,
      'address': instance.address,
      'tel': instance.tel,
      'typeCode': instance.typeCode,
      'taxno': instance.taxNo,
      'priceLevel': instance.priceLevel,
      'provinceId': instance.provinceId,
      'provinceName': instance.provinceName,
      'ampherId': instance.ampherId,
      'ampherName': instance.ampherName,
      'townId': instance.townId,
      'townName': instance.townName,
      'zip': instance.zip,
      'lat': instance.lat,
      'lon': instance.lon,
      'branch': instance.branch,
      'activeStatus': instance.activeStatus,
      'email': instance.email,
      'mobileno': instance.mobileNo,
      'contactperson': instance.contactPerson,
      'updatedate': instance.updateDate,
      'applydate': instance.applyDate,
      'salespersonCode': instance.salesPersonCode,
      'salesPersonName': instance.salespersonName,
      'saleuniTName': instance.saleUnitName,
      'tier': instance.tier,
      'mobilESales': instance.mobileSales,
      'mapCode': instance.mapCode,
      'birthDate': instance.birthDate,
      'gender': instance.gender,
      'agentCode': instance.agentCode,
      'jtoken': instance.jtoken,
      'paramValues1': instance.paramValues1,
      'paramValues2': instance.paramValues2,
      'paramValues3': instance.paramValues3,
      'paramValues4': instance.paramValues4,
      'paramValues5': instance.paramValues5,
      'shopPhotoImage': instance.shopPhotoImage,
      'picFileName': instance.picFileName,
      'personType': instance.personType,
      'accountCode': instance.accountCode,
      'routeStep2': instance.routeStep2,
      'authorizeAmount': instance.authorizeAmount,
      'debtAmount': instance.debtAmount,
      'activeDc': instance.activeDc,
      'activeDcName': instance.activeDcName,
      'activeDeliveryRoute': instance.activeDeliveryRoute,
      'activeSaleCode': instance.activeSaleCode,
      'activeSalesAreaCode': instance.activeSalesAreaCode,
    };
