// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'customer.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Customer _$CustomerFromJson(Map<String, dynamic> json) => Customer(
      json['CUSTOMERCODE'] as String,
      json['CUSTOMERNAME'] as String,
      json['SALEUNIT'] as String,
      json['SALEUNIT_NAME'] as String,
      json['PRIMARYCODE'] as String?,
      json['ADDRESS'] as String?,
      json['TEL'] as String?,
      json['TypeCode'] as String?,
      json['TAXNO'] as String?,
      json['PriceLevel'] as String?,
      json['ProvinceID'] as String?,
      json['ProvinceName'] as String?,
      json['AmpherID'] as String?,
      json['AmpherName'] as String?,
      json['TownID'] as String?,
      json['TownName'] as String?,
      json['ZIP'] as String?,
      json['lat'] as String?,
      json['lon'] as String?,
      json['Branch'] as String?,
      json['ActiveStatus'] as String?,
      json['EMAIL'] as String?,
      json['MOBILENO'] as String?,
      json['CONTACTPERSON'] as String?,
      json['Updatedate'] as String?,
      json['Applydate'] as String?,
      json['Salesperson_Code'] as String?,
      json['Salesperson_Name'] as String?,
      json['TIER'] as String?,
      json['MOBILE_SALES'] as String?,
      json['MapCode'] as String?,
      json['BirthDate'] as String?,
      json['Gender'] as String?,
      json['AgentCode'] as String?,
      json['jtoken'] as String?,
      json['ParamValues1'] as String?,
      json['ParamValues2'] as String?,
      json['ParamValues3'] as String?,
      json['ParamValues4'] as String?,
      json['ParamValues5'] as String?,
      json['ShopPhotoImage'] as String?,
      json['PicFileName'] as String?,
      json['PersonType'] as int,
      json['AccountCode'] as String?,
      json['RouteStep2'] as String?,
      (json['AuthorizeAmount'] as num).toDouble(),
      (json['DebtAmount'] as num).toDouble(),
    );

Map<String, dynamic> _$CustomerToJson(Customer instance) => <String, dynamic>{
      'CUSTOMERCODE': instance.customerCode,
      'CUSTOMERNAME': instance.customerName,
      'SALEUNIT': instance.saleUnit,
      'SALEUNIT_NAME': instance.saleUnitName,
      'PRIMARYCODE': instance.primaryCode,
      'ADDRESS': instance.address,
      'TEL': instance.tel,
      'TypeCode': instance.typeCode,
      'TAXNO': instance.taxNo,
      'PriceLevel': instance.priceLevel,
      'ProvinceID': instance.provinceID,
      'ProvinceName': instance.proviceName,
      'AmpherID': instance.ampherID,
      'AmpherName': instance.ampherName,
      'TownID': instance.townID,
      'TownName': instance.townName,
      'ZIP': instance.zip,
      'lat': instance.lat,
      'lon': instance.lon,
      'Branch': instance.branch,
      'ActiveStatus': instance.activeStatus,
      'EMAIL': instance.email,
      'MOBILENO': instance.mobileNo,
      'CONTACTPERSON': instance.contactPerson,
      'Updatedate': instance.updateDate,
      'Applydate': instance.applyDate,
      'Salesperson_Code': instance.salespersonCode,
      'Salesperson_Name': instance.salespersonName,
      'TIER': instance.tier,
      'MOBILE_SALES': instance.mobileSales,
      'MapCode': instance.mapCode,
      'BirthDate': instance.birthDate,
      'Gender': instance.gender,
      'AgentCode': instance.agentCode,
      'jtoken': instance.jtoken,
      'ParamValues1': instance.paramValues1,
      'ParamValues2': instance.paramValues2,
      'ParamValues3': instance.paramValues3,
      'ParamValues4': instance.paramValues4,
      'ParamValues5': instance.paramValues5,
      'ShopPhotoImage': instance.shopPhotoImage,
      'PicFileName': instance.picFileName,
      'PersonType': instance.personType,
      'AccountCode': instance.accountCode,
      'RouteStep2': instance.routeStep2,
      'AuthorizeAmount': instance.authorizeAmount,
      'DebtAmount': instance.debtAmount,
    };
