// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Product _$ProductFromJson(Map<String, dynamic> json) => Product(
      json['P_Code'] as String,
      json['P_BrandCode'] as String?,
      json['P_Brand'] as String?,
      json['P_GroupCode'] as String?,
      json['P_Group'] as String?,
      json['P_FlavourCode'] as String?,
      json['P_Flavour'] as String?,
      json['P_VarCode'] as String?,
      json['P_Var'] as String?,
      json['P_SizeCode'] as String?,
      json['P_Size'] as String?,
      json['PRODUCTNAME'] as String?,
      json['PRODUCTSHORTNAME'] as String?,
      json['PRODUCTSHORTNAME_TH'] as String?,
      json['PRODUCTSHORTNAME_EN'] as String?,
      json['BARCODE1'] as String?,
      json['BARCODE2'] as String?,
      json['BARCODE3'] as String?,
      json['UNIT1'] as String?,
      json['UNIT1NAME'] as String?,
      json['UNIT1RATE'] as int?,
      json['UNIT2'] as String?,
      json['UNIT2NAME'] as String?,
      json['UNIT2RATE'] as int?,
      json['UNIT3'] as String?,
      json['UNIT3NAME'] as String?,
      json['UNIT3RATE'] as int?,
      (json['SalesPrice'] as num?)?.toDouble(),
      (json['PRICE1'] as num?)?.toDouble(),
      (json['PRICE2'] as num?)?.toDouble(),
      (json['PRICE3'] as num?)?.toDouble(),
      (json['PRICE4'] as num?)?.toDouble(),
      (json['PRICE5'] as num?)?.toDouble(),
      json['PRICE1TYPE'] as String?,
      json['PRICE2TYPE'] as String?,
      json['PRICE3TYPE'] as String?,
      json['PRICE4TYPE'] as String?,
      json['PRICE5TYPE'] as String?,
      json['PIC_FILENAME'] as String?,
      json['PIC_FILENAME2'] as String?,
      json['PIC_FILENAME3'] as String?,
      json['PIC_FILENAME4'] as String?,
      json['PIC_FILENAME5'] as String?,
      json['matype'] as String?,
      json['matypeName'] as String?,
      json['P_Description'] as String?,
      json['free_item'] as bool,
      json['ORDER_UNIT'] as String?,
      (json['SalesPrice1'] as num?)?.toDouble(),
      (json['SalesPrice2'] as num?)?.toDouble(),
      (json['SalesPrice3'] as num?)?.toDouble(),
      json['IsProductAdvancePrice'] as bool,
      (json['promotionproduct'] as List<dynamic>)
          .map((e) => PromotionProduct.fromJson(e as Map<String, dynamic>))
          .toList(),
      (json['Vol'] as num?)?.toDouble(),
      (json['grossweight'] as num?)?.toDouble(),
      json['SUBTITUTE_GOOD'] as String?,
      json['DChain'] as String?,
      json['qty1'] as int?,
      json['qty2'] as int?,
      json['qty3'] as int?,
      json['DeliveryTime'] as String?,
      json['DeliveryBy'] as String?,
      json['SEO_KEYWORD_TH'] as String?,
      json['KPI_UOM'] as String?,
      (json['KPI_Value'] as num?)?.toDouble(),
      json['selected'] as bool?,
      json['SupplierName'] as String?,
      (json['CatalogPrice'] as num?)?.toDouble(),
      (json['StandardPrice1'] as num?)?.toDouble(),
      (json['StandardPrice2'] as num?)?.toDouble(),
      (json['StandardPrice3'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$ProductToJson(Product instance) => <String, dynamic>{
      'P_Code': instance.productCode,
      'P_BrandCode': instance.pBrandCode,
      'P_Brand': instance.pBrand,
      'P_GroupCode': instance.pGroupCode,
      'P_Group': instance.pGroup,
      'P_FlavourCode': instance.pFlavourCode,
      'P_Flavour': instance.pFlavour,
      'P_VarCode': instance.pVarCode,
      'P_Var': instance.pVar,
      'P_SizeCode': instance.pSizeCode,
      'P_Size': instance.pSize,
      'PRODUCTNAME': instance.productName,
      'PRODUCTSHORTNAME': instance.productShortName,
      'PRODUCTSHORTNAME_TH': instance.productShortNameTH,
      'PRODUCTSHORTNAME_EN': instance.productShortNameEN,
      'BARCODE1': instance.barcode1,
      'BARCODE2': instance.barcode2,
      'BARCODE3': instance.barcode3,
      'UNIT1': instance.unit1,
      'UNIT1NAME': instance.unit1Name,
      'UNIT1RATE': instance.unit1Rate,
      'UNIT2': instance.unit2,
      'UNIT2NAME': instance.unit2Name,
      'UNIT2RATE': instance.unit2Rate,
      'UNIT3': instance.unit3,
      'UNIT3NAME': instance.unit3Name,
      'UNIT3RATE': instance.unit3Rate,
      'SalesPrice': instance.salesPrice,
      'PRICE1': instance.price1,
      'PRICE2': instance.price2,
      'PRICE3': instance.price3,
      'PRICE4': instance.price4,
      'PRICE5': instance.price5,
      'PRICE1TYPE': instance.price1Type,
      'PRICE2TYPE': instance.price2Type,
      'PRICE3TYPE': instance.price3Type,
      'PRICE4TYPE': instance.price4Type,
      'PRICE5TYPE': instance.price5Type,
      'PIC_FILENAME': instance.picFileName,
      'PIC_FILENAME2': instance.picFileName2,
      'PIC_FILENAME3': instance.picFileName3,
      'PIC_FILENAME4': instance.picFileName4,
      'PIC_FILENAME5': instance.picFileName5,
      'matype': instance.matype,
      'matypeName': instance.matypeName,
      'P_Description': instance.description,
      'free_item': instance.freeItem,
      'ORDER_UNIT': instance.orderUnit,
      'SalesPrice1': instance.salesPrice1,
      'SalesPrice2': instance.salesPrice2,
      'SalesPrice3': instance.salesPrice3,
      'IsProductAdvancePrice': instance.isProductAdvancePrice,
      'promotionproduct': instance.promotionProduct,
      'Vol': instance.vol,
      'grossweight': instance.grossWeight,
      'SUBTITUTE_GOOD': instance.subtituteGood,
      'DChain': instance.dChain,
      'qty1': instance.qty1,
      'qty2': instance.qty2,
      'qty3': instance.qty3,
      'DeliveryTime': instance.deliveryTime,
      'DeliveryBy': instance.deliveryBy,
      'SEO_KEYWORD_TH': instance.seoKeywordTH,
      'KPI_UOM': instance.kpiUOM,
      'KPI_Value': instance.kpiValue,
      'selected': instance.selected,
      'SupplierName': instance.supplierName,
      'CatalogPrice': instance.catalogPrice,
      'StandardPrice1': instance.standardPrice1,
      'StandardPrice2': instance.standardPrice2,
      'StandardPrice3': instance.standardPrice3,
    };

PromotionProduct _$PromotionProductFromJson(Map<String, dynamic> json) =>
    PromotionProduct()
      ..promotionId = json['promotionid'] as String?
      ..productId = json['productid'] as String?
      ..promotionName = json['promotionname'] as String?
      ..promotionRemark = json['promotionremark'] as String?
      ..dateBegin = json['datebegin'] as String?
      ..dateEnd = json['dateend'] as String?
      ..promotionText = json['promotiontext'] as String?;

Map<String, dynamic> _$PromotionProductToJson(PromotionProduct instance) =>
    <String, dynamic>{
      'promotionid': instance.promotionId,
      'productid': instance.productId,
      'promotionname': instance.promotionName,
      'promotionremark': instance.promotionRemark,
      'datebegin': instance.dateBegin,
      'dateend': instance.dateEnd,
      'promotiontext': instance.promotionText,
    };
